getpy: setup python with uv

diff --git a/bin/getpudb b/bin/getpudb
--- a/bin/getpudb
+++ b/bin/getpudb
@@ -8,56 +8,41 @@ CLASSICO=$(cd $HERE/.. && pwd)
 OP=""
 [[ $NOP == 1 ]] && OP=echo
 
-if [[ -z $VIRTUAL_ENV ]]; then
-	PIP_USER=--user
-else
-	PIP_USER=
+if ! is_command python3; then
+	eprint "Python is not innstalled"
+	exit 1
 fi
-
-NO_PY2=${NO_PY2:-1}
-
-if [[ $NO_PY2 != 1 ]]; then
-	if is_command python2; then
-		runn python2 -m pip install pudb
-		PY2=1
+	
+if ! LOG=0 pip_install pudb; then
+	xinstall git
+	if ! LOG=0 CACHE=0 pip_install git+https://github.com/inducer/pudb.git@main; then
+		tmpdir=$(mktemp -d /tmp/pudb.XXXXXX)
+		cd $tmpdir
+		runn git clone https://github.com/inducer/pudb.git
+		cd pudb
+		if is_command apt-get; then
+			# this is debian-specific right now, as pip/git install is failing on arm
+			xinstall python3-dev
+		fi
+		PIP_USER=
+		[[ -z $VIRTUAL_ENV ]] && PIP_USER=--user
+		# --prefix= is required for install to succeed
+		runn python3 setup.py install $PIP_USER --prefix=
+		cd /tmp
+		$OP rm -rf $tmpdir
 	fi
 fi
-if [[ $NO_PY3 != 1 ]]; then
-	if is_command python3; then
-		xinstall git
-		if ! LOG=0 runn python3 -m pip install $PIP_USER --no-cache-dir git+https://github.com/inducer/pudb.git@main; then
-			if ! LOG=0 runn python3 -m pip install $PIP_USER --no-cache-dir pudb; then
-				tmpdir=$(mktemp -d /tmp/pudb.XXXXXX)
-				cd $tmpdir
-				runn git clone https://github.com/inducer/pudb.git
-				cd pudb
-				if is_command apt-get; then
-					# this is debian-specific right now, as pip/git install is failing on arm
-					xinstall python3-dev
-				fi
-				# --prefix= is required for install to succeed
-				runn python3 setup.py install $PIP_USER --prefix=
-				cd /tmp
-				$OP rm -rf $tmpdir
-				PY3=1
-			else
-				PY3=1
-			fi
-		else
-			PY3=1
-		fi
 
-		pudb=/usr/local/bin/pudb
-		if [[ ! -e $pudb ]]; then
-			pudb_tmp=$(mktemp /tmp/pudb.XXXXXX)
-			cat <<-'EOF' > $pudb_tmp
-				#!/bin/bash
+hash -r
+if ! is_command pudb; then
+	pudb=$HOME/.local/bin/pudb
+	if [[ ! -e $pudb ]]; then
+		cat <<-'EOF' > $pudb
+			#!/bin/bash
 
-				python3 -m pudb "$@"
-				EOF
-			$SUDO cp $pudb_tmp $pudb
-			$SUDO chmod +x $pudb
-		fi
+			python3 -m pudb "$@"
+			EOF
+		chmod +x $pudb
 	fi
 fi
 
@@ -68,55 +53,30 @@ if [[ -f $cfg ]]; then
 	fi
 fi
 
-$OP mkdir -p `dirname $cfg`
-if [[ $PY2 == 1 ]]; then
-	cat <<-'EOF' > $cfg
-		[pudb]
-		breakpoints_weight = 1
-		current_stack_frame = top
-		custom_shell = 
-		custom_stringifier = 
-		custom_theme = 
-		default_variables_access_level = public
-		display = auto
-		hide_cmdline_win = True
-		line_numbers = True
-		prompt_on_quit = False
-		seen_welcome = e042
-		shell = internal
-		sidebar_width = 0.5
-		stack_weight = 1
-		stringifier = repr
-		theme = midnight
-		variables_weight = 1
-		wrap_variables = True
-		EOF
-fi
-
-if [[ $PY3 == 1 ]]; then
-	cat <<-'EOF' > $cfg
-		[pudb]
-		breakpoints_weight = 1
-		current_stack_frame = top
-		custom_shell = 
-		custom_stringifier = 
-		custom_theme = 
-		default_variables_access_level = public
-		display = auto
-		hide_cmdline_win = True
-		hotkeys_breakpoints = B
-		hotkeys_code = C
-		hotkeys_stack = S
-		hotkeys_variables = V
-		line_numbers = True
-		prompt_on_quit = False
-		seen_welcome = e042
-		shell = internal
-		sidebar_width = 0.5
-		stack_weight = 1
-		stringifier = repr
-		theme = midnight
-		variables_weight = 1
-		wrap_variables = True
-		EOF
-fi
+$OP mkdir -p "$(dirname $cfg)"
+cat <<-'EOF' > $cfg
+	[pudb]
+	breakpoints_weight = 1
+	current_stack_frame = top
+	custom_shell = 
+	custom_stringifier = 
+	custom_theme = 
+	default_variables_access_level = public
+	display = auto
+	hide_cmdline_win = True
+	hotkeys_breakpoints = B
+	hotkeys_code = C
+	hotkeys_stack = S
+	hotkeys_variables = V
+	hotkeys_toggle_cmdline_focus = ctrl x
+	line_numbers = True
+	prompt_on_quit = False
+	seen_welcome = e049
+	shell = internal
+	sidebar_width = 0.5
+	stack_weight = 1
+	stringifier = repr
+	theme = monokai
+	variables_weight = 1
+	wrap_variables = True
+	EOF
