shibumi: posh/poshhh split

diff --git a/shibumi/runner b/shibumi/runner
--- a/shibumi/runner
+++ b/shibumi/runner
@@ -86,6 +86,9 @@ spin_while() {
 # posh <<-'END'
 #     commands...
 #     END
+# args:
+#   UTF16=1   utf16 ouput (default)
+#   UTF8=1    utf8 output (convert using iconv)
 
 posh() {
 	local ps_exe=powershell.exe
@@ -98,7 +101,60 @@ posh() {
 	PREFIX=posh SUFFIX=.ps1 heredoc <<-'END'; local cmd="$FILE"
 		$ErrorActionPreference = 'Stop'
 		END
-	cmd="$(cygpath -m "$cmd")"
+	if is_command cygpath; then
+		cmd="$(cygpath -m "$cmd")"
+	fi
+
+	if [[ $(platform_os) == windows ]]; then
+		W_CLASSICO="$(cygpath -m $CLASSICO)"
+		echo "\$CLASSICO=\"$W_CLASSICO\"" >> $cmd
+	fi
+
+	if [[ -t 0 ]]; then
+		echo "$@" >> "$cmd"
+	else
+		cat >> "$cmd"
+	fi
+
+	if [[ $UTF8 == 1 ]]; then
+		{ "$ps_exe" -File "$cmd" 2>&1 | iconv -f UTF-16LE -t UTF-8; local E=$?; } || true
+	else
+		{ "$ps_exe" -File "$cmd"; local E=$?; } || true
+	fi
+
+	rm -f "$cmd"
+	return $E
+}
+
+#----------------------------------------------------------------------------------------------
+
+# usage:
+# poshhh command...
+# or:
+# poshhh <<-'END'
+#     commands...
+#     END
+# args:
+#   NOP=1     Print commands, do not execute
+#   V=n       Verbosity level (0: none, 1: print command, 2: print output)
+#   LOG=1     When command fails, print output
+#   UTF16=1   utf16 ouput (default)
+#   UTF8=1    utf8 output (convert using iconv)
+
+poshhh() {
+	local ps_exe=powershell.exe
+	if is_command pwsh.exe; then
+		ps_exe=pwsh.exe
+	elif [[ -f '/c/Program Files/PowerShell/7/pwsh.exe' ]]; then
+		ps_exe='/c/Program Files/PowerShell/7/pwsh.exe'
+	fi
+
+	PREFIX=posh SUFFIX=.ps1 heredoc <<-'END'; local cmd="$FILE"
+		$ErrorActionPreference = 'Stop'
+		END
+	if is_command cygpath; then
+		cmd="$(cygpath -m "$cmd")"
+	fi
 
 	if [[ $(platform_os) == windows ]]; then
 		W_CLASSICO="$(cygpath -m $CLASSICO)"
@@ -110,20 +166,29 @@ posh() {
 	else
 		cat >> "$cmd"
 	fi
+
 	(( NOP == 1 || V >= 1 )) && cat "$cmd"
 	[[ $NOP == 1 ]] && return
-	if (( V < 2 )); then
+
+	if [[ $V == 2 ]]; then
+		if [[ $UTF8 == 1 ]]; then
+			{ "$ps_exe" -File "$cmd" 2>&1 | iconv -f UTF-16LE -t UTF-8; local E=$?; } || true
+		else
+			{ "$ps_exe" -File "$cmd"; local E=$?; } || true
+		fi
+	else
 		mk_temp log; local log="$FILE"
 		{ "$ps_exe" -File "$cmd" > "$log" 2>&1 ; local E=$?; } || true
-		[[ $E != 0 && $LOG != 0 ]] && cat "$log"
-		rm -f "$log"
-	else
-		if [[ $UTF16 == 1 || $UTF8 != 1 ]]; then
-			{ "$ps_exe" -File "$cmd"; local E=$?; } || true
-		elif [[ $UTF8 == 1 ]]; then
-			{ "$ps_exe" -File "$cmd" 2>&1 | iconv -f UTF-16LE -t UTF-8; local E=$?; } || true
+		if [[ $E != 0 && $LOG != 0 ]]; then
+			if [[ $UTF8 == 1 ]]; then
+				cat "$log" | iconv -f UTF-16LE -t UTF-8
+			else
+				cat "$log"
+			fi
 		fi
+		rm -f "$log"
 	fi
+
 	rm -f "$cmd"
 	return $E
 }
